Add "Get Early Access" page
JoinColony/JoinColony.github.io pull request #125
Opened 2019-08-25 16:13 UTC by ceolson01

## Description

This PR adds the _Get Early Access_ page

**New stuff** ✨

* Dependencies
  * Formik - for better forms
  * yup - for validation
* Get Early Access page

**Changes** 🏗

* Get early access links to new page
* Form in homepage hero pre-fills and redirects to new page

**Demo** 🎥 

![Get Early Access Form](https://user-images.githubusercontent.com/3052635/63652740-51b65080-c729-11e9-93cf-2c71748bdda4.gif)

2019-08-27 14:02 UTC, ryanchristo requested changes
Hmmm... I'm not able to get my email address to transfer over from one page to the other. Maybe something changed since the demo reel? If using `location` in `EarlyAccess`, do we need to call the `withLocation` method at some point to make `location` accessible?

2019-08-27 14:02 UTC, ryanchristo commented on src/modules/core/components/Input/Input.jsx
> +    : getMainClasses(appearance, styles, { hasError: !!error });
Nice use of state. :+1:

2019-08-27 14:02 UTC, ryanchristo commented on src/modules/core/components/Input/Input.jsx
> +        // Always render this div so the UI doesn't shift once an error message exists
Well commented. `showErrorText` is a nice addition too.

2019-08-27 14:02 UTC, ryanchristo commented on src/modules/core/components/Textarea/Textarea.module.css
> +  /* Negative margin to match `Input`s */
:ok_hand:

2019-08-27 14:02 UTC, ryanchristo commented on src/modules/pages/components/Website/EarlyAccess/EarlyAccess.jsx
> +      ? location.state.email
This isn't working for me... `location` is always `undefined` :thinking:

2019-08-27 14:02 UTC, ryanchristo commented on src/modules/pages/components/Website/HomePage/Hero/Hero.jsx
> +    navigate(PAGE_GET_EARLY_ACCESS, { state: { email } });
This looks right but as mentioned above, `location` is always `undefined` in `EarlyAccess`.

2019-08-27 22:34 UTC, ceolson01 commented on src/modules/pages/components/Website/EarlyAccess/EarlyAccess.jsx
> +      ? location.state.email
I've adjusted the props to pass through from gatsby pages. All good now

2019-08-28 11:09 UTC, ryanchristo approved these changes
Nice! Works now! Approved. :+1:

2019-08-28 22:16 UTC, merged